# Generated by Django 4.2.25 on 2025-12-02 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id_competence', models.AutoField(primary_key=True, serialize=False)),
                ('nom_competence', models.CharField(max_length=100, verbose_name='Nom de la compétence')),
                ('niveau_competence', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], max_length=20, verbose_name='Niveau')),
                ('categorie', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('mobile', 'Mobile'), ('devops', 'DevOps'), ('base_donnees', 'Base de données'), ('design', 'Design'), ('autres', 'Autres')], default='autres', max_length=20, verbose_name='Catégorie')),
                ('annees_experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'db_table': 'portfolio_competence',
                'ordering': ['categorie', 'ordre', 'nom_competence'],
                'unique_together': {('utilisateur', 'nom_competence')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_contact', models.AutoField(primary_key=True, serialize=False)),
                ('type_contact', models.CharField(choices=[('email', 'Email'), ('telephone', 'Téléphone'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter'), ('autre', 'Autre')], max_length=20)),
                ('valeur_contact', models.CharField(max_length=255)),
                ('est_principal', models.BooleanField(default=False, verbose_name='Contact principal')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'portfolio_contact',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('titre_projet', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description_projet', models.TextField(verbose_name='Description')),
                ('langage_projet', models.CharField(max_length=100, verbose_name='Langage principal')),
                ('lien_projet', models.URLField(blank=True, null=True, verbose_name='Lien du projet')),
                ('lien_github', models.URLField(blank=True, null=True, verbose_name='Lien GitHub')),
                ('image_projet', models.ImageField(blank=True, null=True, upload_to='projets/', verbose_name='Image du projet')),
                ('technologies', models.JSONField(blank=True, default=list, verbose_name='Technologies utilisées')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('est_public', models.BooleanField(default=True, verbose_name='Public')),
                ('est_termine', models.BooleanField(default=True, verbose_name='Terminé')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'db_table': 'portfolio_projet',
                'ordering': ['ordre', '-date_realisation', 'titre_projet'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id_portfolio', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du portfolio')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('titre_professionnel', models.CharField(blank=True, max_length=200, verbose_name='Titre professionnel')),
                ('biographie', models.TextField(blank=True, verbose_name='Biographie')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='portfolio_photos/', verbose_name='Photo de profil')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('vue_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('theme_couleur', models.CharField(default='#2563eb', max_length=7, verbose_name='Couleur du thème')),
                ('layout_type', models.CharField(default='classique', max_length=50, verbose_name='Type de mise en page')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='Mots-clés')),
                ('afficher_photo', models.BooleanField(default=True, verbose_name='Afficher la photo')),
                ('afficher_competences', models.BooleanField(default=True, verbose_name='Afficher les compétences')),
                ('afficher_projets', models.BooleanField(default=True, verbose_name='Afficher les projets')),
                ('afficher_contacts', models.BooleanField(default=True, verbose_name='Afficher les contacts')),
                ('afficher_formations', models.BooleanField(default=True, verbose_name='Afficher les formations')),
                ('afficher_experiences', models.BooleanField(default=True, verbose_name='Afficher les expériences')),
                ('formations', models.JSONField(blank=True, default=list, verbose_name='Formations')),
                ('experiences', models.JSONField(blank=True, default=list, verbose_name='Expériences')),
                ('langues', models.JSONField(blank=True, default=list, verbose_name='Langues')),
                ('certifications', models.JSONField(blank=True, default=list, verbose_name='Certifications')),
                ('interets', models.JSONField(blank=True, default=list, verbose_name="Centres d'intérêt")),
                ('competences', models.ManyToManyField(blank=True, related_name='portfolios', to='portfolio.competence', verbose_name='Compétences')),
                ('contacts', models.ManyToManyField(blank=True, related_name='portfolios', to='portfolio.contact', verbose_name='Contacts')),
                ('projets', models.ManyToManyField(blank=True, related_name='portfolios', to='portfolio.projet', verbose_name='Projets')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'db_table': 'portfolio_portfolio',
                'ordering': ['-date_modification'],
            },
        ),
    ]
