# Generated by Django 5.2.9 on 2025-12-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='photo_projet',
            field=models.ImageField(blank=True, null=True, upload_to='projet_photos/', verbose_name='Photo du projet'),
        ),
    ]
