# Generated by Django 5.2.9 on 2025-12-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projet_photo_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='photo_projet',
        ),
        migrations.AlterField(
            model_name='projet',
            name='image_projet',
            field=models.ImageField(blank=True, null=True, upload_to='projet_photos/', verbose_name='Photo du projet'),
        ),
    ]
