# Generated by Django 5.2.9 on 2025-12-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_projet_photo_projet_alter_projet_image_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='photo_template',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_template/', verbose_name='Photo de template'),
        ),
    ]
